[package]
name = "collector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.26", features = ["client", "http1", "tcp"]}
serde = { version = "1.0.162", features = ["derive"]}
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.96"
hyper-tls = "0.5.0"
futures = "0.3.28"